In [ ]:
#   --------------
#   |A   B   C | D
#   ---- 
#   |E | F | G   H
#   |      -----  
#   |I   J   K   L
#   |-------------



In [18]:
import numpy as np

In [19]:
gamma = 0.75
alpha = 0.9

In [20]:
# Defining the states
location_to_state = {'A': 0,
                     'B': 1,
                     'C': 2,
                     'D': 3,
                     'E': 4,
                     'F': 5,
                     'G': 6,
                     'H': 7,
                     'I': 8,
                     'J': 9,
                     'K': 10,
                     'L': 11}


In [21]:
# Defining the actions
actions = [0,1,2,3,4,5,6,7,8,9,10,11]

In [22]:
# Defining the rewards


# rows represent the current state and column represent the reward agent will get by doing some action 
# in first row Agent is at Position A and he will get reward only if he moves to position B


#--------------A,B,C,D,E,F,G,H,I,J,K,L
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],    #A
              [1,0,1,0,0,1,0,0,0,0,0,0],    #B
              [0,1,0,0,0,0,1,0,0,0,0,0],    #C
              [0,0,0,0,0,0,0,1,0,0,0,0],    #D
              [0,0,0,0,0,0,0,0,1,0,0,0],    #E
              [0,1,0,0,0,0,0,0,0,1,0,0],    #F
              [0,0,1,0,0,0,1000,1,0,0,0,0], #G
              [0,0,0,1,0,0,1,0,0,0,0,1],    #H
              [0,0,0,0,1,0,0,0,0,1,0,0],    #I
              [0,0,0,0,0,1,0,0,1,0,1,0],    #J
              [0,0,0,0,0,0,0,0,0,1,0,1],    #K
              [0,0,0,0,0,0,0,1,0,0,1,0]])   #L

In [23]:
#Initializing the Q-Values
Q = np.array(np.zeros([12,12]))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
# calulating the Q-Values
for i in range(1000):
    current_state = np.random.randint(0,12)
    playable_actions = []
    for j in range(12):
        if R[current_state, j] > 0:
            playable_actions.append(j)
    next_state = np.random.choice(playable_actions)
    TD = R[current_state, next_state] + gamma*Q[next_state, np.argmax(Q[next_state,])]- Q[current_state, next_state]
    Q[current_state, next_state] = Q[current_state, next_state] + alpha*TD

In [25]:
print("Q-Values:")
print(Q.astype(int))


Q-Values:
[[   0 1688    0    0    0    0    0    0    0    0    0    0]
 [1267    0 2249    0    0 1266    0    0    0    0    0    0]
 [   0 1688    0    0    0    0 2999    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2249    0    0    0    0]
 [   0    0    0    0    0    0    0    0  712    0    0    0]
 [   0 1688    0    0    0    0    0    0    0  949    0    0]
 [   0    0 2250    0    0    0 3998 2250    0    0    0    0]
 [   0    0    0 1688    0    0 2999    0    0    0    0 1687]
 [   0    0    0    0  535    0    0    0    0  949    0    0]
 [   0    0    0    0    0 1264    0    0  713    0 1263    0]
 [   0    0    0    0    0    0    0    0    0  949    0 1688]
 [   0    0    0    0    0    0    0 2249    0    0 1263    0]]


In [26]:
# Making a mapping from the states to the locations
state_to_location = {state: location for location, state in location_to_state.items()}

In [27]:
#final function that will return the optimal route
def route(starting_location, ending_location):
    route = [starting_location]
    next_location = starting_location
    while (next_location != ending_location):
        starting_state = location_to_state[starting_location]
        next_state = np.argmax(Q[starting_state,])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
    return route
print('Route:')
route('E', 'G')

#   --------------
#   |A   B   C | D
#   ---- 
#   |E | F | G   H
#   |      -----  
#   |I   J   K   L
#   |-------------


Route:


['E', 'I', 'J', 'F', 'B', 'C', 'G']

In [ ]:
#   -----------------------Optimized Approach------------------------------

In [28]:


# Defining the rewards
# rows represent the current state and column represent the reward agent will get by doing some action 
# in first row Agent is at Position A and he will get reward only if he moves to position B
# difference from the previous approach is that the reward for final State that is G is not updated to 1000. It will increase automatically

#--------------A,B,C,D,E,F,G,H,I,J,K,L
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0], #A
              [1,0,1,0,0,1,0,0,0,0,0,0], #B
              [0,1,0,0,0,0,1,0,0,0,0,0], #C
              [0,0,0,0,0,0,0,1,0,0,0,0], #D
              [0,0,0,0,0,0,0,0,1,0,0,0], #E
              [0,1,0,0,0,0,0,0,0,1,0,0], #F
              [0,0,1,0,0,0,1,1,0,0,0,0], #G
              [0,0,0,1,0,0,1,0,0,0,0,1], #H
              [0,0,0,0,1,0,0,0,0,1,0,0], #I
              [0,0,0,0,0,1,0,0,1,0,1,0], #J
              [0,0,0,0,0,0,0,0,0,1,0,1], #K
              [0,0,0,0,0,0,0,1,0,0,1,0]])#L


# mapping from the states to the locations
state_to_location = {state: location for location, state in location_to_state.items()}



In [29]:
# function that returns the shortest route from a starting to ending location
def route(starting_location, ending_location):
    R_new = np.copy(R)
    ending_state = location_to_state[ending_location]
    R_new[ending_state, ending_state] = 1000
    Q = np.array(np.zeros([12,12]))
    for i in range(1000):
        current_state = np.random.randint(0,12)
        playable_actions = []
        for j in range(12):
            if R_new[current_state, j] > 0:
                playable_actions.append(j)
        next_state = np.random.choice(playable_actions)
        TD = R_new[current_state, next_state] + gamma * Q[next_state, np.argmax(Q[next_state,])] - Q[current_state, next_state]
        Q[current_state, next_state] = Q[current_state, next_state] + alpha * TD
    route = [starting_location]
    next_location = starting_location
    while (next_location != ending_location):
        starting_state = location_to_state[starting_location]
        next_state = np.argmax(Q[starting_state,])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
    return route



In [30]:

# final function that returns the optimal route
def best_route(starting_location, intermediary_location, ending_location):
    return route(starting_location, intermediary_location) + route(intermediary_location, ending_location)[1:]


print('Route:')
best_route('E', 'K', 'G')


#   --------------
#   |A   B   C | D
#   ---- 
#   |E | F | G   H
#   |      -----  
#   |I   J   K   L
#   |-------------


Route:


['E', 'I', 'J', 'K', 'L', 'H', 'G']